# Generated by Django 3.1.6 on 2021-02-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('hash', models.CharField(max_length=255)),
                ('height', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.IntegerField()),
                ('transactions', models.IntegerField()),
                ('miner', models.CharField(max_length=255)),
            ],
        ),
    ]
