# Generated by Django 3.1.6 on 2021-02-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hash', models.CharField(max_length=255)),
                ('Height', models.IntegerField()),
                ('Version', models.IntegerField()),
                ('PrevHash', models.CharField(max_length=255)),
                ('NextHash', models.CharField(max_length=255)),
                ('MerkleRoot', models.CharField(max_length=255)),
                ('Timestamp', models.IntegerField()),
                ('Bits', models.CharField(max_length=255)),
                ('Nonce', models.IntegerField()),
                ('HashStateRoot', models.CharField(max_length=255)),
                ('HashUTXORoot', models.CharField(max_length=255)),
                ('PrevOutStakeHash', models.CharField(max_length=255)),
                ('PrevOutStakeN', models.IntegerField()),
                ('Signature', models.CharField(max_length=255)),
                ('Chainwork', models.CharField(max_length=255)),
                ('Flags', models.CharField(max_length=100)),
                ('Interval', models.IntegerField()),
                ('Size', models.IntegerField()),
                ('Weight', models.IntegerField()),
                ('Transactions', models.JSONField()),
                ('Miner', models.CharField(max_length=255)),
                ('Difficulty', models.FloatField()),
                ('Reward', models.IntegerField()),
                ('Confirmations', models.IntegerField()),
            ],
        ),
    ]
