# Generated by Django 3.1.6 on 2021-02-08 13:18

from django.db import migrations
import requests

def create_data(apps, schema_editor):
    Block = apps.get_model('blockchain_depiction_app', 'Block')
    data = requests.get("https://bcschain.info/api/blocks").json()
    blocks_id = []
    for datum in data:
        Block(Hash=datum.get("hash"), Height=datum.get("height"), Timestamp=datum.get("timestamp"),
        	 Transactions=datum.get("transactionCount"), Miner=datum.get("miner")).save()

class Migration(migrations.Migration):

    dependencies = [
        ('blockchain_depiction_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),            	
    ]